-- Smallcaps.ai AIM Intelligence — private-beta PostgreSQL schema
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS companies (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), ticker VARCHAR(24) NOT NULL UNIQUE, company_name VARCHAR(255) NOT NULL, isin VARCHAR(32) NOT NULL DEFAULT '', market VARCHAR(32) NOT NULL DEFAULT 'AIM', sector VARCHAR(128) NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS announcements (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE, source_id VARCHAR(160) NOT NULL UNIQUE, published_at TIMESTAMPTZ NOT NULL, headline VARCHAR(500) NOT NULL, announcement_type VARCHAR(100) NOT NULL DEFAULT 'Other', source_url TEXT NOT NULL DEFAULT '', source_urls JSONB NOT NULL DEFAULT '[]'::jsonb, source_note TEXT NOT NULL DEFAULT '', evidence_status VARCHAR(32) NOT NULL DEFAULT 'complete' CHECK (evidence_status IN ('complete','partial','unavailable','metadata-only')), evidence_retrieved_at TIMESTAMPTZ, raw_text TEXT NOT NULL, categories JSONB NOT NULL DEFAULT '[]'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS ix_announcements_company_published ON announcements(company_id, published_at DESC);
CREATE INDEX IF NOT EXISTS ix_announcements_evidence_status ON announcements(evidence_status);

CREATE TABLE IF NOT EXISTS analyst_runs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), announcement_id UUID NOT NULL REFERENCES announcements(id) ON DELETE CASCADE, impact_colour VARCHAR(16) NOT NULL CHECK (impact_colour IN ('green','amber','red','grey')), impact_score INTEGER NOT NULL CHECK (impact_score BETWEEN 1 AND 5), impact_level VARCHAR(16) NOT NULL CHECK (impact_level IN ('low','medium','high','critical')), impact_rationale TEXT NOT NULL DEFAULT '', impact_drivers JSONB NOT NULL DEFAULT '[]'::jsonb, headline VARCHAR(500) NOT NULL, takeaway TEXT NOT NULL, new_information JSONB NOT NULL DEFAULT '[]'::jsonb, reiterated_information JSONB NOT NULL DEFAULT '[]'::jsonb, what_changed JSONB NOT NULL, analyst_view TEXT NOT NULL, supports_case JSONB NOT NULL DEFAULT '[]'::jsonb, challenges_case JSONB NOT NULL DEFAULT '[]'::jsonb, watch_items JSONB NOT NULL DEFAULT '[]'::jsonb, disclosure_assessment JSONB NOT NULL DEFAULT '{}'::jsonb, source_references JSONB NOT NULL DEFAULT '[]'::jsonb, source_warnings JSONB NOT NULL DEFAULT '[]'::jsonb, quality_status VARCHAR(16) NOT NULL DEFAULT 'publishable' CHECK (quality_status IN ('publishable','review','blocked')), quality_flags JSONB NOT NULL DEFAULT '[]'::jsonb, confidence DOUBLE PRECISION NOT NULL DEFAULT 0.8 CHECK (confidence BETWEEN 0 AND 1), prompt_version VARCHAR(80) NOT NULL, model_version VARCHAR(120) NOT NULL, analysis_version VARCHAR(120) NOT NULL, is_current BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS ix_analyst_runs_announcement_created ON analyst_runs(announcement_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_analyst_runs_quality ON analyst_runs(quality_status, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_analyst_runs_one_current ON analyst_runs(announcement_id) WHERE is_current;

CREATE TABLE IF NOT EXISTS facts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE, announcement_id UUID NOT NULL REFERENCES announcements(id) ON DELETE CASCADE, analyst_run_id UUID NOT NULL REFERENCES analyst_runs(id) ON DELETE CASCADE, ordinal INTEGER NOT NULL DEFAULT 0, label VARCHAR(255) NOT NULL, metric VARCHAR(160) NOT NULL DEFAULT '', period VARCHAR(80) NOT NULL DEFAULT '', value VARCHAR(255) NOT NULL, unit VARCHAR(40) NOT NULL DEFAULT '', currency VARCHAR(16) NOT NULL DEFAULT '', as_of_date VARCHAR(40) NOT NULL DEFAULT '', value_numeric DOUBLE PRECISION, value_low DOUBLE PRECISION, value_high DOUBLE PRECISION, basis VARCHAR(32) NOT NULL CHECK (basis IN ('reported','calculated','not-disclosed','source-warning')), note TEXT NOT NULL DEFAULT '', comparator TEXT NOT NULL DEFAULT '', comparator_type VARCHAR(40) NOT NULL DEFAULT 'none', comparator_source_id VARCHAR(160) NOT NULL DEFAULT '', previous_value VARCHAR(255) NOT NULL DEFAULT '', information_status VARCHAR(32) NOT NULL DEFAULT 'new', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), CHECK (value_low IS NULL OR value_high IS NULL OR value_low <= value_high));
CREATE INDEX IF NOT EXISTS ix_facts_company_metric_period ON facts(company_id, metric, period, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_facts_run_ordinal ON facts(analyst_run_id, ordinal);

CREATE TABLE IF NOT EXISTS guidance_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE, announcement_id UUID NOT NULL REFERENCES announcements(id) ON DELETE CASCADE, analyst_run_id UUID NOT NULL REFERENCES analyst_runs(id) ON DELETE CASCADE, ordinal INTEGER NOT NULL DEFAULT 0, metric VARCHAR(160) NOT NULL, period VARCHAR(80) NOT NULL DEFAULT '', value VARCHAR(255) NOT NULL DEFAULT '', status VARCHAR(32) NOT NULL, comparator TEXT NOT NULL DEFAULT '', previous_value VARCHAR(255) NOT NULL DEFAULT '', previous_source_id VARCHAR(160) NOT NULL DEFAULT '', information_status VARCHAR(32) NOT NULL DEFAULT 'new', note TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS ix_guidance_company_metric_period ON guidance_events(company_id, metric, period, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_guidance_run_ordinal ON guidance_events(analyst_run_id, ordinal);

CREATE TABLE IF NOT EXISTS management_claims (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE, announcement_id UUID NOT NULL REFERENCES announcements(id) ON DELETE CASCADE, analyst_run_id UUID NOT NULL REFERENCES analyst_runs(id) ON DELETE CASCADE, ordinal INTEGER NOT NULL DEFAULT 0, claim TEXT NOT NULL, claim_key VARCHAR(160) NOT NULL DEFAULT '', metric VARCHAR(160) NOT NULL DEFAULT '', target_value VARCHAR(255) NOT NULL DEFAULT '', target_date VARCHAR(80) NOT NULL DEFAULT '', status VARCHAR(32) NOT NULL DEFAULT 'open', outcome TEXT NOT NULL DEFAULT '', evidence TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS ix_claims_company_status ON management_claims(company_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_claims_company_key ON management_claims(company_id, claim_key, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_claims_run_ordinal ON management_claims(analyst_run_id, ordinal);

CREATE TABLE IF NOT EXISTS price_reactions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), announcement_id UUID NOT NULL REFERENCES announcements(id) ON DELETE CASCADE, reaction_session VARCHAR(32) NOT NULL, previous_close DOUBLE PRECISION, open_price DOUBLE PRECISION, latest_price DOUBLE PRECISION, close_price DOUBLE PRECISION, event_day_return DOUBLE PRECISION, return_1d DOUBLE PRECISION, return_5d DOUBLE PRECISION, return_20d DOUBLE PRECISION, currency VARCHAR(16) NOT NULL DEFAULT 'GBp', source VARCHAR(120) NOT NULL DEFAULT '', observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE (announcement_id, reaction_session));
CREATE TABLE IF NOT EXISTS corrections (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), analyst_run_id UUID NOT NULL REFERENCES analyst_runs(id) ON DELETE CASCADE, field_path VARCHAR(255) NOT NULL, original_value JSONB, corrected_value JSONB, reason TEXT NOT NULL, corrected_by VARCHAR(120) NOT NULL DEFAULT 'owner', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS ix_corrections_analyst_run ON corrections(analyst_run_id, created_at DESC);
CREATE TABLE IF NOT EXISTS job_runs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), job_name VARCHAR(80) NOT NULL, run_key VARCHAR(160) NOT NULL DEFAULT '', status VARCHAR(24) NOT NULL DEFAULT 'running' CHECK (status IN ('running','success','degraded','failed','skipped')), started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), finished_at TIMESTAMPTZ, summary JSONB NOT NULL DEFAULT '{}'::jsonb, warnings JSONB NOT NULL DEFAULT '[]'::jsonb, error_text TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS ix_job_runs_name_started ON job_runs(job_name, started_at DESC);
CREATE INDEX IF NOT EXISTS ix_job_runs_status ON job_runs(status, started_at DESC);
